import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/SessionProviderWrapper";
import { Providers } from './providers';
import Script from 'next/script';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased interactive-element`}>
        <SessionWrapper>
          <Providers>{children}</Providers>
        </SessionWrapper>
        <Script src="/interactive.js" />
      </body>
    </html>
  );
}
